### ISSUE TITLE
sim_miltiplier.bat not working?

### ISSUE THREAD

**Issue by lukipedio** [johonkanen/ac_inout_psu#29]
The source\math_library\multiplier\simulation\sim_miltiplier.bat simulation batch seems not working in my case.

Setting of project_root variable doesn't work and it is not used anyway.

If I remove all unused or problematic stuff and keep it to the base bone, I still have issue with VCD.

![image](https://user-images.githubusercontent.com/16959881/129445808-dc3795b1-eb4c-4d06-a3ef-c6422b3b85ab.png)

I am working on a Windows 10 machine with GHDL/Gtkwave.

![image](https://user-images.githubusercontent.com/16959881/129445819-f18dd64d-499d-4ab6-b061-e23540da5e67.png)

**Comment by johonkanen** [comment]
The script assumes that git is in the path since it uses git for searching for the project root. It should be useable from commandline with writing
 sim_multiplier.bat 0
 in the folder where the .bat script is found

**Comment by lukipedio** [comment]
`git rev-parse --show-toplevel 
`
works fine on the terminal.

![image](https://user-images.githubusercontent.com/16959881/129448141-dbcb7359-523c-41bc-ac71-7bdb54c05b70.png)

In my case GTKwave is causing an issue.

**Comment by lukipedio** [comment]
which version of GHDL/GTKwave are you using?

**Comment by lukipedio** [comment]
oh VCD file has 0 B size .. I should check better

**Comment by lukipedio** [comment]
ok. The simulation is running now.
switched to stable ghdl v0.37. I was using an unstable one. sorry.
I would need to understand using the project_root variable if unused. An intermediate step to completion?

**Comment by johonkanen** [comment]
The rooting is used for the script find source paths relative to project root.  If there are common modules that are used, then only one set of paths need to be maintained. This would help with refactoring since moving sources to different folders should not break anything.

This is a part of the as of yet not implemented unit test run script

**Comment by lukipedio** [comment]
OK, got it.
